module.exports = {
	ACCESS_TOKEN_TIME: 60 * 60,
	SALT_ROUNDS: 5,
	SQUADHELP_BANK_NUMBER: '4564654564564564',
	SQUADHELP_BANK_NAME: 'SquadHelp',
	SQUADHELP_BANK_CVC: '453',
	SQUADHELP_BANK_EXPIRY: '11/22',
	CUSTOMER: 'customer',
	CREATOR: 'creator',
	CREATOR_ENTRIES: 'creator_entries',
	CONTEST_STATUS_ACTIVE: 'active',
	CONTEST_STATUS_FINISHED: 'finished',
	CONTEST_STATUS_PENDING: 'pending',
	NAME_CONTEST: 'name',
	LOGO_CONTEST: 'logo',
	TAGLINE_CONTEST: 'tagline',
	OFFER_STATUS_PENDING: 'pending',
	OFFER_STATUS_REJECTED: 'rejected',
	OFFER_STATUS_WON: 'won',
	FILES_PATH: 'public/',
	STATIC_PATH_LOG_FILE: 'logs',
	STATIC_NAME_LOG_FILE: 'errors.log',
	STATIC_PATH_LOG_FILE_CURRENT_DAY: 'logsCurrentDay',
	SOCKET_CONNECTION: 'connection',
	SOCKET_SUBSCRIBE: 'subscribe',
	SOCKET_UNSUBSCRIBE: 'unsubscribe',
	SOCKET_SUBSCRIBE_CHAT: 'subscribeChat',
	SOCKET_UNSUBSCRIBE_CHAT: 'unsubscribeChat',
	NOTIFICATION_ENTRY_CREATED: 'onEntryCreated',
	NOTIFICATION_CHANGE_MARK: 'changeMark',
	NOTIFICATION_CHANGE_OFFER_STATUS: 'changeOfferStatus',
	NEW_MESSAGE: 'newMessage',
	CHANGE_BLOCK_STATUS: 'CHANGE_BLOCK_STATUS',
	CONTEST_TYPE: [
		'',
		'name,tagline,logo',
		'name',
		'tagline',
		'logo',
		'name,tagline',
		'logo,tagline',
		'name,logo',
	],
};
