version: '3'

services:

  client-dev:
    build:
      context: ./client
    environment:
      NODE_ENV: development
    depends_on:
      - server-dev
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:5000"

  server-dev:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - db-dev
      - mongo-dev
    volumes:
      - ./public/images:/public/images
      - ./server:/server
      - /server/node_modules

  mongo-dev:
    image: mongo:6.0.3
    ports:
      - "27040:27017"

  db-dev:
    image: postgres:15.1-alpine
    env_file:
      - ./server/.env
    ports:
      - "5440:5432"

volumes:
  server-dev:
