const ACTION_TYPES = {
	//AUTH
	AUTH_LOGIN_ACTION: 'AUTH_LOGIN_ACTION',
	AUTH_REGISTRATION_ACTION: 'AUTH_REGISTRATION_ACTION',
	AUTH_REQUEST: 'AUTH_REQUEST',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_ERROR: 'AUTH_ERROR',
	AUTH_ACTION_CLEAR: 'AUTH_ACTION_CLEAR',
	AUTH_CLEAR_ERROR: 'AUTH_CLEAR_ERROR',

	//*****************************************************************

	//USER

	//getUser (userReducer)
	GET_USER_ACTION: 'GET_USER_ACTION',
	GET_USER_REQUEST: 'GET_USER_REQUEST',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_ERROR: 'GET_USER_ERROR',
	//userStore
	CLEAR_USER_STORE: 'CLEAR_USER_STORE',
	//updateUser
	UPDATE_USER_ACTION: 'UPDATE_USER_ACTION',
	UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
	UPDATE_USER_ERROR: 'UPDATE_USER_ERROR',
	//clearErrorUpdateUser
	CLEAR_USER_ERROR: 'CLEAR_USER_ERROR',

	//UserProfile (userProfileReducer)
	CHANGE_EDIT_MODE_ON_USER_PROFILE: 'CHANGE_EDIT_MODE_ON_USER_PROFILE',
	CHANGE_PROFILE_MODE_VIEW: 'CHANGE_PROFILE_MODE_VIEW',

	//******************************************************************

	//GET CONTEST
	//getContests
	GET_CONTESTS_CUSTOMER_ACTION: 'GET_CONTESTS_CUSTOMER_ACTION',
	GET_CONTESTS_CREATIVE_ACTION: 'GET_CONTESTS_CREATIVE_ACTION',
	GET_CONTESTS_MODERATOR_ACTION: 'GET_CONTESTS_MODERATOR_ACTION',
	GET_CONTESTS_REQUEST: 'GET_CONTESTS_REQUEST',
	GET_CONTESTS_SUCCESS: 'GET_CONTESTS_SUCCESS',
	GET_CONTESTS_ERROR: 'GET_CONTESTS_ERROR',
	SET_NEW_CUSTOMER_FILTER: 'SET_NEW_CUSTOMER_FILTER',
	SET_NEW_CREATOR_FILTER: 'SET_NEW_CREATOR_FILTER',
	CLEAR_CONTESTS_LIST: 'CLEAR_CONTESTS_LIST',
	//getDataForContest
	GET_DATA_FOR_CONTEST_ACTION: 'GET_DATA_FOR_CONTEST_ACTION',
	GET_DATA_FOR_CONTEST_REQUEST: 'GET_DATA_FOR_CONTEST_REQUEST',
	GET_DATA_FOR_CONTEST_SUCCESS: 'GET_DATA_FOR_CONTEST_SUCCESS',
	GET_DATA_FOR_CONTEST_ERROR: 'GET_DATA_FOR_CONTEST_ERROR',
	CLEAR_PREFERENCE: 'CLEAR_PREFERENCE',

	//CREATE CONTEST
	//bundle
	SELECT_BUNDLE_ACTION: 'SELECT_BUNDLE_ACTION',
	CLEAR_BUNDLE_ACTION: 'CLEAR_BUNDLE_ACTION',
	//storeContestReducer
	SAVE_CONTEST_TO_STORE: 'SAVE_CONTEST_TO_STORE',
	CLEAR_CONTEST_STORE: 'CLEAR_CONTEST_STORE',

	//GET CONTEST BY ID
	//getContestById
	GET_CONTEST_BY_ID_ACTION: 'GET_CONTEST_BY_ID',
	GET_CONTEST_BY_ID_REQUEST: 'GET_CONTEST_BY_ID_REQUEST',
	GET_CONTEST_BY_ID_SUCCESS: 'GET_CONTEST_BY_ID_SUCCESS',
	GET_CONTEST_BY_ID_ERROR: 'GET_CONTEST_BY_ID_ERROR',
	CLEAR_CONTEST_BY_ID: 'CLEAR_CONTEST_BY_ID',
	//changeEditContest
	CHANGE_EDIT_CONTEST: 'CHANGE_EDIT_CONTEST',
	//changeViewMode
	CHANGE_CONTEST_VIEW_MODE: 'CHANGE_CONTEST_VIEW_MODE',
	//changeShowImage
	CHANGE_SHOW_IMAGE: 'CHANGE_SHOW_IMAGE',
	//updateStoreAfterUpdateContest
	UPDATE_STORE_AFTER_UPDATE_CONTEST: 'UPDATE_STORE_AFTER_UPDATE_CONTEST',
	//getCountOffersByContest
	GET_COUNT_OFFERS_BY_CONTEST_ACTION: 'GET_COUNT_OFFERS_BY_CONTEST_ACTION',
	GET_COUNT_OFFERS_BY_CONTEST_REQUEST: 'GET_COUNT_OFFERS_BY_CONTEST_REQUEST',
	GET_COUNT_OFFERS_BY_CONTEST_SUCCESS: 'GET_COUNT_OFFERS_BY_CONTEST_SUCCESS',
	GET_COUNT_OFFERS_BY_CONTEST_ERROR: 'GET_COUNT_OFFERS_BY_CONTEST_ERROR',

	// UPDATE CONTEST
	//updateContest
	UPDATE_CONTEST_ACTION: 'UPDATE_CONTEST_ACTION',
	UPDATE_CONTEST_REQUEST: 'UPDATE_CONTEST_REQUEST',
	UPDATE_CONTEST_ERROR: 'UPDATE_CONTEST_ERROR',
	CLEAR_UPDATE_CONTEST_STORE: 'CLEAR_UPDATE_CONTEST_STORE',

	//******************************************************************

	//OFFER
	//getAllOffersByContestId
	GET_ALL_OFFER_BY_CONTEST_ID_ACTION: 'GET_ALL_OFFER_BY_CONTEST_ID_ACTION',
	GET_ALL_OFFER_BY_CONTEST_ID_REQUEST: 'GET_ALL_OFFER_BY_CONTEST_ID_REQUEST',
	GET_ALL_OFFER_BY_CONTEST_ID_SUCCESS: 'GET_ALL_OFFER_BY_CONTEST_ID_SUCCESS',
	GET_ALL_OFFER_BY_CONTEST_ID_ERROR: 'GET_ALL_OFFER_BY_CONTEST_ID_ERROR',
	//setOfferStatus
	SET_OFFER_STATUS_ACTION: 'SET_OFFER_STATUS_ACTION',
	SET_OFFER_STATUS_REQUEST: 'SET_OFFER_STATUS_REQUEST',
	SET_OFFER_STATUS_SUCCESS: 'SET_OFFER_STATUS_SUCCESS',
	SET_OFFER_STATUS_ERROR: 'SET_OFFER_STATUS_ERROR',
	SET_OFFER_STATUS_MODERATOR_ACTION: 'SET_OFFER_STATUS_MODERATOR_ACTION',
	SET_OFFER_STATUS_MODERATOR_SUCCESS: 'SET_OFFER_STATUS_MODERATOR_SUCCESS',
	//addOffer
	ADD_NEW_OFFER_ACTION: 'ADD_NEW_OFFER_ACTION',
	ADD_NEW_OFFER_REQUEST: 'ADD_NEW_OFFER_REQUEST',
	ADD_NEW_OFFER_SUCCESS: 'ADD_NEW_OFFER_SUCCESS',
	ADD_NEW_OFFER_ERROR: 'ADD_NEW_OFFER_ERROR',
	//deleteOffer
	DELETE_OFFER_ACTION: 'DELETE_OFFER_ACTION',
	DELETE_OFFER_REQUEST: 'DELETE_OFFER_REQUEST',
	DELETE_OFFER_SUCCESS: 'DELETE_OFFER_SUCCESS',
	DELETE_OFFER_ERROR: 'DELETE_OFFER_ERROR',
	//changeMark
	CHANGE_MARK_REQUEST: 'CHANGE_MARK_REQUEST',
	CHANGE_MARK_ACTION: 'CHANGE_MARK_ACTION',
	CHANGE_MARK_SUCCESS: 'CHANGE_MARK_SUCCESS',
	CHANGE_MARK_ERROR: 'CHANGE_MARK_ERROR',
	//offerStoreCleareError
	OFFER_STORE_CLEARE_ERROR: 'OFFER_STORE_CLEARE_ERROR',
	//offerStoreCleareOffersStore
	OFFER_STORE_CLEARE_OFFERS_STORE: 'OFFER_STORE_CLEARE_OFFERS_STORE',

	//*****************************************************************

	//PAYMETS
	CASHOUT_ACTION: 'CASHOUT_ACTION',
	PAYMENT_ACTION: 'PAYMENT_ACTION',
	PAYMENT_REQUEST: 'PAYMENT_REQUEST',
	PAYMENT_ERROR: 'PAYMENT_ERROR',
	PAYMENT_CLEAR_ERROR: 'PAYMENT_CLEAR_ERROR',
	CHANGE_FOCUS_ON_CARD: 'CHANGE_FOCUS_ON_CARD',
	CLEAR_PAYMENT_STORE: 'CLEAR_PAYMENT_STORE',

	//***************************************************************

	//CHAT MODE
	//changeChatShow
	CHANGE_CHAT_SHOW: 'CHANGE_CHAT_SHOW',
	//changeTypeOfChatAdding
	CHANGE_TYPE_ADDING_CHAT_IN_CATALOG: 'CHANGE_TYPE_ADDING_CHAT_IN_CATALOG',
	//changeShowAddChatToCatalogMenu
	CHANGE_SHOW_ADD_CHAT_TO_CATALOG: 'CHANGE_SHOW_ADD_CHAT_TO_CATALOG',
	//setPreviewChatMode
	SET_CHAT_PREVIEW_MODE: 'SET_CHAT_PREVIEW_MODE',
	//changeShowModeCatalog
	CHANGE_SHOW_MODE_CATALOG: 'CHANGE_SHOW_MODE_CATALOG',
	//changeRenameCatalogMode
	CHANGE_RENAME_CATALOG_MODE: 'CHANGE_RENAME_CATALOG_MODE',

	//CHAT
	//getPreviewChat
	GET_PREVIEW_CHAT_ACTION: 'GET_PREVIEW_CHAT_ACTION',
	GET_PREVIEW_CHAT_SUCCESS: 'GET_PREVIEW_CHAT_SUCCESS',
	GET_PREVIEW_CHAT_ERROR: 'GET_PREVIEW_CHAT_ERROR',
	//sendMessage
	SEND_MESSAGE_ACTION: 'SEND_MESSAGE_ACTION',
	SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
	SEND_MESSAGE_ERROR: 'SEND_MESSAGE_ERROR',


	//CHAT CATALOG
	//getCatalogList
	GET_CATALOG_LIST_ACTION: 'GET_CATALOG_LIST_ACTION',
	GET_CATALOG_LIST_SUCCESS: 'GET_CATALOG_LIST_SUCCESS',
	GET_CATALOG_LIST_ERROR: 'GET_CATALOG_LIST_ERROR',
	//createCatalog
	CREATE_CATALOG_ACTION: 'CREATE_CATALOG_ACTION',
	CREATE_CATALOG_SUCCESS: 'CREATE_CATALOG_SUCCESS',
	CREATE_CATALOG_ERROR: 'CREATE_CATALOG_ERROR',
	//addChatToCatalog
	ADD_CHAT_TO_CATALOG_ACTION: 'ADD_CHAT_TO_CATALOG_ACTION',
	ADD_CHAT_TO_CATALOG_SUCCESS: 'ADD_CHAT_TO_CATALOG_SUCCESS',
	ADD_CHAT_TO_CATALOG_ERROR: 'ADD_CHAT_TO_CATALOG_ERROR',
	//changeCatalogName
	CHANGE_CATALOG_NAME_ACTION: 'CHANGE_CATALOG_NAME_ACTION',
	CHANGE_CATALOG_NAME_SUCCESS: 'CHANGE_CATALOG_NAME_SUCCESS',
	CHANGE_CATALOG_NAME_ERROR: 'CHANGE_CATALOG_NAME_ERROR',
	//deleteCatalog
	DELETE_CATALOG_ACTION: 'DELETE_CATALOG_ACTION',
	DELETE_CATALOG_SUCCESS: 'DELETE_CATALOG_SUCCESS',
	DELETE_CATALOG_ERROR: 'DELETE_CATALOG_ERROR',
	//removeChatFromCatalog
	REMOVE_CHAT_FROM_CATALOG_ACTION: 'REMOVE_CHAT_FROM_CATALOG_ACTION',
	REMOVE_CHAT_FROM_CATALOG_SUCCESS: 'REMOVE_CHAT_FROM_CATALOG_SUCCESS',
	REMOVE_CHAT_FROM_CATALOG_ERROR: 'REMOVE_CHAT_FROM_CATALOG_ERROR',

	//CHAT DIALOG
	//getDialog
	GET_DIALOG_MESSAGES_ACTION: 'GET_DIALOG_MESSAGES_ACTION',
	GET_DIALOG_MESSAGES_SUCCESS: 'GET_DIALOG_MESSAGES_SUCCESS',
	GET_DIALOG_MESSAGES_ERROR: 'GET_DIALOG_MESSAGES_ERROR',
	//clearMessageList
	CLEAR_MESSAGE_LIST: 'CLEAR_MESSAGE_LIST',

	//CHAT MANAGMENT OPERATIONS
	//backToDialogList
	BACK_TO_DIALOG_LIST: 'BACK_TO_DIALOG_LIST',
	//changeChatFavorite
	CHANGE_CHAT_FAVORITE_ACTION: 'CHANGE_CHAT_FAVORITE_ACTION',
	CHANGE_CHAT_FAVORITE_SUCCESS: 'CHANGE_CHAT_FAVORITE_SUCCESS',
	CHANGE_CHAT_FAVORITE_ERROR: 'CHANGE_CHAT_FAVORITE_ERROR',
	//changeChatBlock
	CHANGE_CHAT_BLOCK_ACTION: 'CHANGE_CHAT_BLOCK_ACTION',
	CHANGE_CHAT_BLOCK_SUCCESS: 'CHANGE_CHAT_BLOCK_SUCCESS',
	CHANGE_CHAT_BLOCK_ERROR: 'CHANGE_CHAT_BLOCK_ERROR',
	//goToExpandedDialog
	GO_TO_EXPANDED_DIALOG: 'GO_TO_EXPANDED_DIALOG',
	//clearChatError
	CLEAR_CHAT_ERROR: 'CLEAR_CHAT_ERROR',
	//clearChat
	CLEAR_CHAT: 'CLEAR_CHAT',

};

export default ACTION_TYPES;
